### ISSUE TITLE
`reduce-kv` doesn't appear to work on records

### ISSUE THREAD

**Issue by djblue** [basilisp-lang/basilisp#1102]
https://github.com/djblue/basilisp/commit/039b1427e89bbadcaed4500851e3bc05a9115030 for an exact test case to reproduce.

If you have any pointers on how to solve this, I'm down to try.

**Comment by chrisrink10** [comment]
Thanks for the bug report.

I would guess there are 2 options for how to address this one:
1. We could just extend the [`KVReduce` protocol](https://github.com/basilisp-lang/basilisp/blob/ce3eb81c5c0c645dabe9a39404307ba5de41b959/src/basilisp/core/protocols.lpy#L30), or
2. We could add `IKVReduce` to the [`defrecord` macro](https://github.com/basilisp-lang/basilisp/blob/766850375e22644696d116b801dac2f96405417a/src/basilisp/core.lpy#L6817)

I don't have a strong preference for either option, although I suspect (2) will be a little more annoying to write since it's deep in a large macro.
