### ISSUE TITLE
basisisp dependencies versions

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#805]
Hi,

most of the python dependencies in Basilisp are all fixed with a caret. This can prevent from installing Basilisp in environments where packages are constrained to a particular version.

For example, the `pyrsistent` dependency is declared as

``` toml
pyrsistent = "^0.18.0"
```

requiring that a 0.18.x version is available in the environment. This can prevent Basilisp from installing when any other package in the environment is dependent/constrained  on a higher version (e.g. 0.19.x).

Would it be possible to change the Basilisp dependency to accommodate a wider range of its dependencies versions (.e.g. >=0.18.0)?

I suppose, if we go down this road, we could also have some limited integration tests for each dependency that is deemed having a big effect in basilisp.

Also, while at it, `pyrsistent` appears to support maps, can we fold in the immutable maps into it and remove the `immutables` dependency? Less dependencies, less likely for it to cause issue when installing Basilisp in python environments with diverse package and dependencies requirements.

Thanks 

latest `pyrsistent` versions as of today
<img src="https://github.com/basilisp-lang/basilisp/assets/34983288/f5ad1596-4998-4bf2-8f76-c6497eacf7ad" width="300">

**Comment by chrisrink10** [comment]
> This can prevent Basilisp from installing when any other package in the environment is dependent/constrained on a higher version (e.g. 0.19.x).

We can open up Pyrsistent to `>=0.18.0,<1.0.0`. This is a quirk of the [caret dependency](https://python-poetry.org/docs/dependency-specification/#caret-requirements) for `0.x` versioned dependencies. For >=1.0 it would translate to `>=1.18.0,<2.0.0` which is what I would want.

> I suppose, if we go down this road, we could also have some limited integration tests for each dependency that is deemed having a big effect in basilisp.

I use caret dependencies in general to avoid changes due to major version increases. With the exception of Immutables and Pyrsistent, I feel comfortable with the current pins.

> Also, while at it, pyrsistent appears to support maps, can we fold in the immutable maps into it and remove the immutables dependency? Less dependencies, less likely for it to cause issue when installing Basilisp in python environments with diverse package and dependencies requirements.

I moved away from Pyrsistent for maps intentionally in #559 to get a C map implementation. Pyrsistent only has a C implementation of the vector type and a Python version of a map which uses the C vector under the hood. I do not wish to switch back. Immutables uses a HAMT which is specifically the same underlying data structure used in Clojure.

**Comment by chrisrink10** [comment]
I put up #806 to loosen those two dependencies which should allow you to use 0.19.
