### ISSUE TITLE
`int` fn compatibility

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#875]
The `int` fn coerces its input to an integer.

While Clojure and Basilisp results match for numerical inputs, they differ when the input is characters or strings

- Clojure fails on string inputs and converts a character to their ASCII/unicode index value
- Basilisp will attempt to parse a string as a base 10 number.

e.g.
Clojure
``` clojure
user> (int "9")
Execution error (ClassCastException) at user/eval8834 (REPL:966).
class java.lang.String cannot be cast to class java.lang.Character (java.lang.String and java.lang.Character are in module java.base of loader 'bootstrap')

user> (int \9)
57
```

Basilisp
``` clojure
basilisp.user=> (int "9")
9
```

Do we want (1) to document the differences in this case or (2) opt for Clojure compatibility aligning the case of a single character string with Clojure, and perhaps provide an alternative `python/int` for what is currently `int` in Basilisp?

Thanks

**Comment by chrisrink10** [comment]
I would accept a patch document the difference on the docstring, but I do not believe this is a problem and I do not wish to change the behavior of the implementation.

The Clojure version is surprising and requires the use of Java specific `(Integer/parseInt "9")` to get what is an otherwise obvious result. I have always found this difficult and unidiomatic, which is why I did not emulate the behavior when I first implemented it.
